stages:
  - homologacao
  - producao

homologacao:
  stage: homologacao
  tags:
    - front-homologacao
  environment:
    name: homologacao
  script:
    - cd /home/bitflix/homolog/front-end
    - git pull https://ci-homolog-b:ci-homolog-b@gitlab.com/bitflix/front-end homolog
    - git checkout homolog
    - whoami
    - npm i
    - CI=false npm run build
    - pm2 restart homologacao-react-panel
  only:
    - homolog
    - merge-request

producao:
  stage: producao
  tags:
    - front-producao
  environment:
    name: producao
  script:
    - cd /usr/share/nginx/html/meuml/
    - git pull https://ci-homolog-b:ci-homolog-b@gitlab.com/bitflix/front-end.git master
    - git checkout master
    - whoami
    - npm i
    - CI=false npm run build
  only:
    - master
    - merge-request

