stages:
  - homologacao
  - producao

homologacao:
  stage: homologacao
  tags:
    - front-homologacao
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$ALCATRA_PRIVATE_KEY" > ~/.ssh/id_rsa_bitflix_homologacao
    - chmod 600 ~/.ssh/id_rsa
  environment:
    name: homologacao
  script:
    - cd /home/bitflix/homolog/front-end
    - git pull https://ci-homolog-b:ci-homolog-b@gitlab.com/bitflix/front-end
    - git checkout homolog
    - whoami
    - npm run build
    - pm2 restart homologacao-react-panel
  only:
    - homolog
    - merge-request


producao:
  stage: producao
  tags:
    - front-producao
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$ALCATRA_PRIVATE_KEY" > ~/.ssh/id_rsa_bitflix_producao
    - chmod 600 ~/.ssh/id_rsa
  environment:
    name: producao
  script:
    - cd /home/bitflix/producao/front-end && git pull https://ci-homolog-b:ci-homolog-b@gitlab.com/bitflix/front-end master && git checkout master
    - npm run build && npm run start
  only:
    - master
    - merge-request
